INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('3','Lettering');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('4','Marketing & Negócios');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('5','Biografias e Casos Verdadeiros');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('6','Empreendedorismo');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('7','Motivacional');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('8','Planejamento Estratégico');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('9','Literatura infanto-juvenil');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('10','Vendas');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('11','Ficção Policial');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('12','Naufrágios');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('13','Línguas');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('14','Clientes');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('15','Finanças e Investimento');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('16','Carreira Profissinal');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('17','Psicologia');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('18','Comércio Eletrônico');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('19','Desenvolvimento de Software');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('20','Ficção de Fantasia');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('21','Liderança');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('22','Transformação Pessoal');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('23','Programação de computadores');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('24','Astronomia');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('25','Desenvolvimento Pessoal');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('26','Ficção Americana');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('27','Sistemas e Planejamento');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('28','Romance');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('29','Autoestima');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('30','Crimes reais');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('31','Cristandade Religião e Espiritualidade');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('32','Ficção');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('33','Política Literatura e Ficção');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('34','Judaica História Mundial');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('35','Ficção Inglesa');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('36','Ficção Religiosa Literatura e Ficção');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('37','Thrillers Crime, Suspense e Mistério');
INSERT INTO `estante`.`categories` (`id`,`name`) VALUES ('38','Literatura Italiana');
